### ISSUE TITLE
Nice one... any idea if the scrolling time can be controlled? For a slow scrolling feature

### ISSUE THREAD

**Issue by galliumsoft** [brianmcallister/react-auto-scroll#4]

**Comment by brianmcallister** [comment]
That's a really good idea, however as of right now, there are no options for the scrolling behavior. I'm using [scroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior) in order to achieve this effect, and everything is controlled by the browser.

It would certainly be possible to use a JavaScript solution to handle the scrolling, but I'm not sure if the extra complexity is warranted.

However, if there were a bunch of people using this component who wanted that as a feature, I would definitely consider it.

Thanks for the feedback!

**Comment by natashajaved** [comment]
I would be interested in similar feature where we could control the time for scroll. Plus another great feature would be having an estimate for how long would it take to reach bottom, useful to give an idea to user how much more data is to be scrolled this end is reached. Appreciate any help.

**Comment by brian-mcallister-lab49** [comment]
Hey @natashajaved thanks for the input. On the second question... does the scroll bar not solve that problem? I'm on macOS, and I can always see the scrollbar on my machine, but I'm very aware that the scrollbar could change appearance on other platforms and other specific contexts.

Let me know what you think, and if there's a case where the scrollbar is either not visible or doesn't address your needs, maybe some sort of indicator UI would be a possible addition.
